#app
server:
    port: 8080

#spring
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/papaya?useUnicode=yes
      username: root
      password: 123456
    session:
      store-type: none

#security
security:
    basic:
      enabled:  true

papaya.security:
      browser:
#        loginPage: /demo-login.html
        loginType: REDIRECT
      validateCode:
        imageCode:
          width: 100
          height: 50
          length: 6
          expried: 60
          urls: /user,/user/*


#liquibase
liquibase:
    change-log: classpath:/config/liquibase/master.xml
    user: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/papaya
    enabled: true
    drop-first: false

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.papaya.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false